image:
  file: .gitpod.Dockerfile
tasks:
  - name: Run Fileserver + Proxy
    init: npm install
    command: npm start

  - name: Build Elm Frontend
    before: |
      mkdir /workspace/.npm-global
      npm config set prefix '/workspace/.npm-global'
      npm install -g elm-test elm-format
    command: npm run fe

  - name: Run Haskell Backend
    init: |
      cabal update
      stack build
    command: npm run be

ports:
  - port: 3000
    onOpen: notify
  - port: 3001
    onOpen: ignore

vscode:
  extensions:
    - haskell.haskell
    - elmTooling.elm-ls-vscode
